FROM python:latest

ENV PYTHONUNBUFFERED=1 DOCKER=1 DEBIAN_FRONTEND=noninteractive

RUN apt-get update
# Create basic project structure
RUN mkdir -p /code/

WORKDIR /code

ADD project/requirements.txt requirements.txt
RUN pip install -r requirements.txt --no-cache-dir

RUN echo "Europe/Moscow" > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata

EXPOSE 8000